"""update sub files

Revision ID: 200846a09c41
Revises: a95722149d8b
Create Date: 2025-11-03 11:33:41.661209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "200846a09c41"
down_revision: Union[str, None] = "a95722149d8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submission_files", sa.Column("file_id", sa.String(), nullable=False)
    )
    op.alter_column(
        "submission_files",
        "submission_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "submission_files",
        "assignment_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.drop_constraint(
        "submission_files_submission_id_fkey",
        "submission_files",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "submission_files",
        "submission",
        ["submission_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("submission_files", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submission_files",
        sa.Column(
            "content", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "submission_files", type_="foreignkey")
    op.create_foreign_key(
        "submission_files_submission_id_fkey",
        "submission_files",
        "submission",
        ["submission_id"],
        ["id"],
    )
    op.alter_column(
        "submission_files",
        "assignment_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        "submission_files",
        "submission_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.drop_column("submission_files", "file_id")
    # ### end Alembic commands ###
