"""add indexes

Revision ID: 3d9dfff491b2
Revises: 5b608a4ccf4d
Create Date: 2026-03-04 09:11:16.149692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9dfff491b2'
down_revision: Union[str, None] = '5b608a4ccf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment', 'execution_timeout_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_assignment_discipline_id', 'assignment', ['discipline_id'], unique=False)
    op.create_index('ix_assignment_user_id', 'assignment', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'assignment', ['id'])
    op.create_index('ix_assignment_file_assignment_id', 'assignment_file', ['assignment_id'], unique=False)
    op.create_index('ix_assignment_file_assignment_id_file_type', 'assignment_file', ['assignment_id', 'file_type'], unique=False)
    op.create_index('ix_discipline_teacher_discipline_id', 'discipline_teacher', ['discipline_id'], unique=False)
    op.create_index('ix_discipline_teacher_teacher_id', 'discipline_teacher', ['teacher_id'], unique=False)
    op.create_index('ix_refresh_token_token', 'refresh_token', ['token'], unique=False)
    op.create_index('ix_refresh_token_user_id', 'refresh_token', ['user_id'], unique=False)
    op.create_index('ix_submission_assignment_id', 'submission', ['assignment_id'], unique=False)
    op.create_index('ix_submission_user_id', 'submission', ['user_id'], unique=False)
    op.create_index('ix_submission_user_id_assignment_id', 'submission', ['user_id', 'assignment_id'], unique=False)
    op.create_index('ix_submission_file_assignment_id', 'submission_file', ['assignment_id'], unique=False)
    op.create_index('ix_submission_file_submission_id', 'submission_file', ['submission_id'], unique=False)
    op.create_index('ix_user_group_id', 'user', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_group_id', table_name='user')
    op.drop_index('ix_submission_file_submission_id', table_name='submission_file')
    op.drop_index('ix_submission_file_assignment_id', table_name='submission_file')
    op.drop_index('ix_submission_user_id_assignment_id', table_name='submission')
    op.drop_index('ix_submission_user_id', table_name='submission')
    op.drop_index('ix_submission_assignment_id', table_name='submission')
    op.drop_index('ix_refresh_token_user_id', table_name='refresh_token')
    op.drop_index('ix_refresh_token_token', table_name='refresh_token')
    op.drop_index('ix_discipline_teacher_teacher_id', table_name='discipline_teacher')
    op.drop_index('ix_discipline_teacher_discipline_id', table_name='discipline_teacher')
    op.drop_index('ix_assignment_file_assignment_id_file_type', table_name='assignment_file')
    op.drop_index('ix_assignment_file_assignment_id', table_name='assignment_file')
    op.drop_constraint(None, 'assignment', type_='unique')
    op.drop_index('ix_assignment_user_id', table_name='assignment')
    op.drop_index('ix_assignment_discipline_id', table_name='assignment')
    op.alter_column('assignment', 'execution_timeout_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
