"""add file_link to assignments_file

Revision ID: 543cbc49a6ae
Revises: 78d5ccabbb65
Create Date: 2025-11-06 16:27:48.714945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "543cbc49a6ae"
down_revision: Union[str, None] = "78d5ccabbb65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_files", sa.Column("file_link", sa.String(), nullable=False)
    )
    op.alter_column(
        "assignment_files",
        "assignment_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "assignment_files",
        "file_type",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "assignment_files",
        "file_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assignment_files", "file_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "assignment_files",
        "file_type",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "assignment_files",
        "assignment_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.drop_column("assignment_files", "file_link")
    # ### end Alembic commands ###
