"""uuid2

Revision ID: 64c037fe16fb
Revises: 9980ea3edc59
Create Date: 2025-04-28 16:22:05.384754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c037fe16fb'
down_revision: Union[str, None] = '9980ea3edc59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('new_id', sa.UUID(), nullable=False, unique=True))
    # Удалить старый столбец id
    op.drop_column('submission', 'id')
    # Переименовать новый столбец в id
    op.alter_column('submission', 'new_id', new_column_name='id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='unique')
    op.alter_column('submission', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
