"""add created_at to submissions

Revision ID: 78d5ccabbb65
Revises: c216bcddf186
Create Date: 2025-11-04 14:06:54.266350

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78d5ccabbb65"
down_revision: Union[str, None] = "c216bcddf186"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submission", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submission", "created_at")
    # ### end Alembic commands ###
