"""init created_at

Revision ID: 81469d90b8ca
Revises: cfa2f5348609
Create Date: 2025-09-14 18:57:20.167704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81469d90b8ca"
down_revision: Union[str, None] = "cfa2f5348609"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Добавляем колонку с server_default=NOW()
    op.add_column(
        "assignments",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=True,  # временно разрешаем NULL
        ),
    )

    # 2. Обновляем старые записи
    op.execute(
        "UPDATE assignments SET created_at = NOW() WHERE created_at IS NULL"
    )

    # 3. Запрещаем NULL
    op.alter_column("assignments", "created_at", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignments", "created_at")
    # ### end Alembic commands ###
