"""uuid

Revision ID: 9980ea3edc59
Revises: 7740d05322e9
Create Date: 2025-04-28 16:09:42.307320

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9980ea3edc59"
down_revision: Union[str, None] = "7740d05322e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Удалить ограничение внешнего ключа, которое ссылается на столбец id в assignments
    op.drop_constraint(
        "submission_assignment_id_fkey", "submission", type_="foreignkey"
    )

    # Добавить новый столбец UUID в таблицу assignments
    op.add_column(
        "assignments",
        sa.Column("new_id", sa.UUID(), nullable=False, unique=True),
    )

    # Удалить старый столбец id
    op.drop_column("assignments", "id")

    # Переименовать новый столбец в id
    op.alter_column("assignments", "new_id", new_column_name="id")

    # Обновить столбец id как первичный ключ
    op.create_primary_key("pk_assignments", "assignments", ["id"])

    # Повторить процесс для других таблиц, например, для 'submission'
    op.add_column(
        "submission", sa.Column("new_assignment_id", sa.UUID(), nullable=False)
    )

    op.drop_column("submission", "assignment_id")
    op.alter_column(
        "submission", "new_assignment_id", new_column_name="assignment_id"
    )

    # Добавить новое ограничение внешнего ключа, ссылающееся на новый столбец id в assignments
    op.create_foreign_key(
        "submission_assignment_id_fkey",
        "submission",  # Таблица, которая ссылается на внешнюю таблицу
        "assignments",  # Таблица, на которую ссылается внешний ключ
        ["assignment_id"],  # Столбец внешнего ключа
        ["id"],  # Столбец, на который ссылается внешний ключ
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "submission",
        "assignment_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "submission",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignments",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
