"""fix all models)

Revision ID: 9c2cc5d40370
Revises: addeff3df863
Create Date: 2026-02-26 16:50:26.093551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c2cc5d40370'
down_revision: Union[str, None] = 'addeff3df863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # submission links to users/assignments from legacy schema;
    # make drops idempotent and order-safe for PostgreSQL.
    op.execute("ALTER TABLE submission DROP CONSTRAINT IF EXISTS submission_assignment_id_fkey")
    op.execute("ALTER TABLE submission DROP CONSTRAINT IF EXISTS submission_user_id_fkey")

    op.drop_table('assignment_files')
    op.drop_table('submission_files')
    op.drop_table('refresh_tokens')
    op.drop_table('assignments')
    op.drop_table('disciplines')
    op.drop_table('users')
    op.drop_table('groups')

    op.create_table('group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=15), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('google_token', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
    'discipline_teacher',
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
    sa.Column('discipline_id', sa.Integer(), sa.ForeignKey('discipline.id'), nullable=False),
    sa.Column('teacher_id', sa.Integer(), sa.ForeignKey('user.id'), nullable=False),
    sa.UniqueConstraint('discipline_id', 'teacher_id', name='uq_discipline_teacher')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_time', sa.Time(), nullable=False),
    sa.Column('number_of_attempts', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    
    # Legacy rows in submission reference dropped plural tables.
    # Clean them before attaching new FKs to singular tables.
    op.execute("DELETE FROM submission")

    op.create_foreign_key(None, 'submission', 'assignment', ['assignment_id'], ['id'])
    op.create_foreign_key(None, 'submission', 'user', ['user_id'], ['id'])
    op.create_table('assignment_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_link', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.create_foreign_key('submission_user_id_fkey', 'submission', 'users', ['user_id'], ['id'])
    op.create_foreign_key('submission_assignment_id_fkey', 'submission', 'assignments', ['assignment_id'], ['id'])
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('google_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('google_token', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='users_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('google_id', name='users_google_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('assignments',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('due_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('number_of_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('discipline_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], name='assignments_discipline_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='assignments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pk_assignments'),
    sa.UniqueConstraint('id', name='assignments_new_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='refresh_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='refresh_tokens_pkey')
    )
    op.create_table('disciplines',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('disciplines_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name='disciplines_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='disciplines_pkey'),
    sa.UniqueConstraint('teacher_id', 'name', name='uq_teacher_discipline'),
    postgresql_ignore_search_path=False
    )
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('groups_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='groups_pkey'),
    sa.UniqueConstraint('name', name='groups_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('submission_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name='submission_files_assignment_id_fkey'),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], name='submission_files_submission_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='submission_files_pkey')
    )
    op.create_table('assignment_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name='assignment_files_assignment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assignment_files_pkey')
    )
    op.drop_table('submission_file')
    op.drop_table('assignment_file')
    op.drop_table('assignment')
    op.drop_table('refresh_token')
    op.drop_table('discipline')
    op.drop_table('user')
    op.drop_table('group')
    # ### end Alembic commands ###
