"""empty message

Revision ID: a7cf583b5dd3
Revises: a9a34041c816
Create Date: 2025-09-25 17:39:12.468943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7cf583b5dd3"
down_revision: Union[str, None] = "a9a34041c816"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("submission", sa.Column("feedback", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submission", "feedback")
    # ### end Alembic commands ###
