"""update assignments files

Revision ID: a95722149d8b
Revises: 449235321641
Create Date: 2025-10-27 14:23:06.990721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a95722149d8b'
down_revision: Union[str, None] = '449235321641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_files', sa.Column('file_id', sa.String(), nullable=True))
    op.drop_column('assignment_files', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_files', sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('assignment_files', 'file_id')
    # ### end Alembic commands ###
