"""update disciplines

Revision ID: addeff3df863
Revises: 4329813ae8d0
Create Date: 2026-02-24 16:38:02.723438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'addeff3df863'
down_revision: Union[str, None] = '4329813ae8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_teacher_discipline', 'disciplines', ['teacher_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_teacher_discipline', 'disciplines', type_='unique')
    # ### end Alembic commands ###
