"""update users

Revision ID: c216bcddf186
Revises: 200846a09c41
Create Date: 2025-11-04 10:50:56.437325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c216bcddf186"
down_revision: Union[str, None] = "200846a09c41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("google_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("google_token", sa.String(length=1024), nullable=True),
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["google_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users",
        "role",
        existing_type=sa.Enum("STUDENT", "TUTOR", "ADMIN", name="userrole"),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("users", "google_token")
    op.drop_column("users", "google_id")
    # ### end Alembic commands ###
