"""add atempts

Revision ID: ed95ecb31e3a
Revises: 3d9dfff491b2
Create Date: 2026-03-14 19:16:31.098038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed95ecb31e3a'
down_revision: Union[str, None] = '3d9dfff491b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_attempt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.JSON(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_link', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_submission_attempt_assignment_id', 'submission_attempt', ['assignment_id'], unique=False)
    op.create_index('ix_submission_attempt_submission_id', 'submission_attempt', ['submission_id'], unique=False)
    op.create_index('ix_submission_attempt_user_id', 'submission_attempt', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submission_attempt_user_id', table_name='submission_attempt')
    op.drop_index('ix_submission_attempt_submission_id', table_name='submission_attempt')
    op.drop_index('ix_submission_attempt_assignment_id', table_name='submission_attempt')
    op.drop_table('submission_attempt')
    # ### end Alembic commands ###
