"""update submission files

Revision ID: ef42d3dd6660
Revises: 543cbc49a6ae
Create Date: 2025-11-07 16:01:39.574150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef42d3dd6660'
down_revision: Union[str, None] = '543cbc49a6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_files', sa.Column('file_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_files', 'file_link')
    # ### end Alembic commands ###
