"""update assignments

Revision ID: fe8df10e92c7
Revises: ef42d3dd6660
Create Date: 2025-11-07 17:33:40.079738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe8df10e92c7"
down_revision: Union[str, None] = "ef42d3dd6660"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments", sa.Column("discipline_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "assignments", "disciplines", ["discipline_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "assignments", type_="foreignkey")
    op.drop_column("assignments", "discipline_id")
    # ### end Alembic commands ###
